fixed TypeError in run-tests.py for single file
Problem:
Python threw a TypeError when running the following:

$ run-tests.py -f examples/bd2.proto
Traceback (most recent call last):
  File "/home/hkz/research/faial/./run-tests.py", line 155, in <module>
    main()
  File "/home/hkz/research/faial/./run-tests.py", line 150, in main
    run_one_test(file=Path(args.file))
TypeError: run_one_test() missing 1 required positional argument: 'solver'

Solution:
The 'solver' parameter of function run_one_test() is unused in the
function.  Or anywhere else in the program.  As such, this commit
removes it.  Rerunning the above now returns without error:

$ ./run-tests.py -f examples/bd2.proto
Program is data-race free!